In [81]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
import xgboost as xgb

from sklearn.metrics import accuracy_score


In [82]:
dataset = pd.read_csv("asthma_data.csv")

In [84]:
dataset

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0          5034   63       0          1               0  15.848744        0   
1          5035   26       1          2               2  22.757042        0   
2          5036   57       0          2               1  18.395396        0   
3          5037   40       1          2               1  38.515278        0   
4          5038   61       0          0               3  19.283802        0   
...         ...  ...     ...        ...             ...        ...      ...   
2387       7421   43       1          0               2  29.059613        0   
2388       7422   18       1          0               1  20.740850        0   
2389       7423   54       0          3               2  37.079560        0   
2390       7424   46       1          0               2  23.444712        0   
2391       7425   26       1          0               0  28.123021        1   

      PhysicalActivity  DietQuality  SleepQuality  ...  LungFunctionFEV1  \
0             0.894448     5.488696      8.701003  ...          1.369051   
1             5.897329     6.341014      5.153966  ...          2.197767   
2             6.739367     9.196237      6.840647  ...          1.698011   
3             1.404503     5.826532      4.253036  ...          3.032037   
4             4.604493     3.127048      9.625799  ...          3.470589   
...                ...          ...           ...  ...               ...   
2387          3.019854     6.119637      8.300960  ...          3.125249   
2388          5.805180     4.386992      7.731192  ...          1.132977   
2389          4.735169     8.214064      7.483521  ...          1.685962   
2390          9.672637     7.362861      6.717272  ...          3.481549   
2391          1.613138     7.412878      8.512253  ...          2.280613   

      LungFunctionFVC  Wheezing  ShortnessOfBreath  ChestTightness  Coughing  \
0            4.941206         0                  0               1         0   
1            1.702393         1                  0               0         1   
2            5.022553         1                  1               1         0   
3            2.300159         1                  0               1         1   
4            3.067944         1                  1               1         0   
...               ...       ...                ...             ...       ...   
2387         5.166032         0                  1               0         0   
2388         5.509502         0                  0               0         1   
2389         3.346877         1                  0               1         1   
2390         1.713274         0                  1               1         0   
2391         2.453284         1                  1               0         0   

      NighttimeSymptoms  ExerciseInduced  Diagnosis  DoctorInCharge  
0                     0                1          0       Dr_Confid  
1                     1                1          0       Dr_Confid  
2                     1                1          0       Dr_Confid  
3                     1                0          0       Dr_Confid  
4                     0                1          0       Dr_Confid  
...                 ...              ...        ...             ...  
2387                  0                1          1       Dr_Confid  
2388                  1                0          1       Dr_Confid  
2389                  0                1          1       Dr_Confid  
2390                  1                1          0       Dr_Confid  
2391                  1                0          0       Dr_Confid  

[2392 rows x 29 columns]

In [85]:
dataset.shape

(2392, 29)

In [86]:
dataset.isna().sum()

PatientID                 0
Age                       0
Gender                    0
Ethnicity                 0
EducationLevel            0
BMI                       0
Smoking                   0
PhysicalActivity          0
DietQuality               0
SleepQuality              0
PollutionExposure         0
PollenExposure            0
DustExposure              0
PetAllergy                0
FamilyHistoryAsthma       0
HistoryOfAllergies        0
Eczema                    0
HayFever                  0
GastroesophagealReflux    0
LungFunctionFEV1          0
LungFunctionFVC           0
Wheezing                  0
ShortnessOfBreath         0
ChestTightness            0
Coughing                  0
NighttimeSymptoms         0
ExerciseInduced           0
Diagnosis                 0
DoctorInCharge            0
dtype: int64

In [87]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   PatientID               2392 non-null   int64  
 1   Age                     2392 non-null   int64  
 2   Gender                  2392 non-null   int64  
 3   Ethnicity               2392 non-null   int64  
 4   EducationLevel          2392 non-null   int64  
 5   BMI                     2392 non-null   float64
 6   Smoking                 2392 non-null   int64  
 7   PhysicalActivity        2392 non-null   float64
 8   DietQuality             2392 non-null   float64
 9   SleepQuality            2392 non-null   float64
 10  PollutionExposure       2392 non-null   float64
 11  PollenExposure          2392 non-null   float64
 12  DustExposure            2392 non-null   float64
 13  PetAllergy              2392 non-null   int64  
 14  FamilyHistoryAsthma     2392 non-null   

In [88]:
dataset.drop(columns = ["DoctorInCharge"], inplace = True)

In [89]:
dataset

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0          5034   63       0          1               0  15.848744        0   
1          5035   26       1          2               2  22.757042        0   
2          5036   57       0          2               1  18.395396        0   
3          5037   40       1          2               1  38.515278        0   
4          5038   61       0          0               3  19.283802        0   
...         ...  ...     ...        ...             ...        ...      ...   
2387       7421   43       1          0               2  29.059613        0   
2388       7422   18       1          0               1  20.740850        0   
2389       7423   54       0          3               2  37.079560        0   
2390       7424   46       1          0               2  23.444712        0   
2391       7425   26       1          0               0  28.123021        1   

      PhysicalActivity  DietQuality  SleepQuality  ...  \
0             0.894448     5.488696      8.701003  ...   
1             5.897329     6.341014      5.153966  ...   
2             6.739367     9.196237      6.840647  ...   
3             1.404503     5.826532      4.253036  ...   
4             4.604493     3.127048      9.625799  ...   
...                ...          ...           ...  ...   
2387          3.019854     6.119637      8.300960  ...   
2388          5.805180     4.386992      7.731192  ...   
2389          4.735169     8.214064      7.483521  ...   
2390          9.672637     7.362861      6.717272  ...   
2391          1.613138     7.412878      8.512253  ...   

      GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
0                          0          1.369051         4.941206         0   
1                          0          2.197767         1.702393         1   
2                          0          1.698011         5.022553         1   
3                          0          3.032037         2.300159         1   
4                          0          3.470589         3.067944         1   
...                      ...               ...              ...       ...   
2387                       0          3.125249         5.166032         0   
2388                       0          1.132977         5.509502         0   
2389                       0          1.685962         3.346877         1   
2390                       1          3.481549         1.713274         0   
2391                       0          2.280613         2.453284         1   

      ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
0                     0               1         0                  0   
1                     0               0         1                  1   
2                     1               1         0                  1   
3                     0               1         1                  1   
4                     1               1         0                  0   
...                 ...             ...       ...                ...   
2387                  1               0         0                  0   
2388                  0               0         1                  1   
2389                  0               1         1                  0   
2390                  1               1         0                  1   
2391                  1               0         0                  1   

      ExerciseInduced  Diagnosis  
0                   1          0  
1                   1          0  
2                   1          0  
3                   0          0  
4                   1          0  
...               ...        ...  
2387                1          1  
2388                0          1  
2389                1          1  
2390                1          0  
2391                0          0  

[2392 rows x 28 columns]

In [90]:
dataset['Diagnosis'].value_counts()

0    2268
1     124
Name: Diagnosis, dtype: int64

**The Dataset is unbalanced**

**0 -> not sick**

**1 -> sick**

In [92]:
dataset.groupby('Diagnosis').mean()

PatientID        Age    Gender  Ethnicity  EducationLevel  \
Diagnosis                                                                
0          6170.587302  42.214286  0.492945   0.665785        1.305556   
1          7307.032258  40.741935  0.500000   0.741935        1.338710   

                 BMI   Smoking  PhysicalActivity  DietQuality  SleepQuality  \
Diagnosis                                                                     
0          27.265959  0.143298          5.048347     5.025009      7.011713   
1          26.859284  0.112903          5.114679     4.983685      7.152516   

           ...  HayFever  GastroesophagealReflux  LungFunctionFEV1  \
Diagnosis  ...                                                       
0          ...  0.255291                0.156085          2.543863   
1          ...  0.217742                0.193548          2.634555   

           LungFunctionFVC  Wheezing  ShortnessOfBreath  ChestTightness  \
Diagnosis                                                                 
0                 3.732240  0.593034           0.502205        0.507937   
1                 3.906432  0.653226           0.467742        0.419355   

           Coughing  NighttimeSymptoms  ExerciseInduced  
Diagnosis                                                
0          0.506173           0.604938         0.598765  
1          0.451613           0.556452         0.717742  

[2 rows x 27 columns]

In [93]:
notsick = dataset[dataset.Diagnosis == 0]
sick = dataset[dataset.Diagnosis == 1]

In [94]:
notsick

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0          5034   63       0          1               0  15.848744        0   
1          5035   26       1          2               2  22.757042        0   
2          5036   57       0          2               1  18.395396        0   
3          5037   40       1          2               1  38.515278        0   
4          5038   61       0          0               3  19.283802        0   
...         ...  ...     ...        ...             ...        ...      ...   
2383       7417   62       1          0               2  20.033593        0   
2385       7419   19       1          1               2  37.913891        0   
2386       7420    5       0          0               1  32.940790        0   
2390       7424   46       1          0               2  23.444712        0   
2391       7425   26       1          0               0  28.123021        1   

      PhysicalActivity  DietQuality  SleepQuality  ...  \
0             0.894448     5.488696      8.701003  ...   
1             5.897329     6.341014      5.153966  ...   
2             6.739367     9.196237      6.840647  ...   
3             1.404503     5.826532      4.253036  ...   
4             4.604493     3.127048      9.625799  ...   
...                ...          ...           ...  ...   
2383          5.276410     9.545336      6.279582  ...   
2385          5.595540     3.120986      4.122047  ...   
2386          8.705633     2.110108      9.261652  ...   
2390          9.672637     7.362861      6.717272  ...   
2391          1.613138     7.412878      8.512253  ...   

      GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
0                          0          1.369051         4.941206         0   
1                          0          2.197767         1.702393         1   
2                          0          1.698011         5.022553         1   
3                          0          3.032037         2.300159         1   
4                          0          3.470589         3.067944         1   
...                      ...               ...              ...       ...   
2383                       0          1.827517         3.757340         1   
2385                       0          3.849256         4.910336         0   
2386                       0          2.948935         2.332723         1   
2390                       1          3.481549         1.713274         0   
2391                       0          2.280613         2.453284         1   

      ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
0                     0               1         0                  0   
1                     0               0         1                  1   
2                     1               1         0                  1   
3                     0               1         1                  1   
4                     1               1         0                  0   
...                 ...             ...       ...                ...   
2383                  0               1         1                  1   
2385                  1               1         1                  0   
2386                  1               0         0                  1   
2390                  1               1         0                  1   
2391                  1               0         0                  1   

      ExerciseInduced  Diagnosis  
0                   1          0  
1                   1          0  
2                   1          0  
3                   0          0  
4                   1          0  
...               ...        ...  
2383                0          0  
2385                1          0  
2386                1          0  
2390                1          0  
2391                0          0  

[2268 rows x 28 columns]

In [95]:
sick

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
2152       7186   31       1          0               0  15.962873        0   
2153       7187   45       1          0               0  18.836049        0   
2154       7188   69       1          0               2  18.094707        0   
2160       7194   49       1          1               0  17.310073        0   
2161       7195   60       1          0               2  32.713025        0   
...         ...  ...     ...        ...             ...        ...      ...   
2381       7415   65       1          0               2  21.132937        0   
2384       7418   31       0          0               2  31.821008        1   
2387       7421   43       1          0               2  29.059613        0   
2388       7422   18       1          0               1  20.740850        0   
2389       7423   54       0          3               2  37.079560        0   

      PhysicalActivity  DietQuality  SleepQuality  ...  \
2152          8.164127     0.032833      5.065319  ...   
2153          4.429940     0.438220      4.431921  ...   
2154          5.648944     4.736220      8.946940  ...   
2160          6.746501     8.885441      6.077918  ...   
2161          0.416681     9.026695      4.751102  ...   
...                ...          ...           ...  ...   
2381          7.024412     2.935468      6.105681  ...   
2384          8.516835     3.532328      9.442670  ...   
2387          3.019854     6.119637      8.300960  ...   
2388          5.805180     4.386992      7.731192  ...   
2389          4.735169     8.214064      7.483521  ...   

      GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
2152                       0          1.289722         1.856247         0   
2153                       0          1.439283         3.185382         1   
2154                       1          2.076774         1.993044         0   
2160                       0          2.328614         5.757570         1   
2161                       1          3.419582         2.621883         1   
...                      ...               ...              ...       ...   
2381                       0          2.794848         5.309860         0   
2384                       1          1.883568         2.592148         0   
2387                       0          3.125249         5.166032         0   
2388                       0          1.132977         5.509502         0   
2389                       0          1.685962         3.346877         1   

      ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
2152                  0               1         0                  1   
2153                  1               1         0                  1   
2154                  1               1         0                  1   
2160                  1               0         0                  0   
2161                  1               1         1                  0   
...                 ...             ...       ...                ...   
2381                  0               0         1                  1   
2384                  0               0         0                  1   
2387                  1               0         0                  0   
2388                  0               0         1                  1   
2389                  0               1         1                  0   

      ExerciseInduced  Diagnosis  
2152                1          1  
2153                1          1  
2154                0          1  
2160                1          1  
2161                0          1  
...               ...        ...  
2381                1          1  
2384                1          1  
2387                1          1  
2388                0          1  
2389                1          1  

[124 rows x 28 columns]

In [96]:
notsick_sample = notsick.sample(n=124)

**Concantinate datasets(notsick_sample and sick datasets)**

In [97]:
data = pd.concat([notsick_sample, sick], axis=0)

In [98]:
data

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
1314       6348   50       1          0               2  33.187808        0   
277        5311   25       0          0               1  31.720048        0   
936        5970   37       0          1               0  33.728561        0   
267        5301   47       0          1               0  35.866880        0   
1192       6226   34       1          0               0  32.722947        0   
...         ...  ...     ...        ...             ...        ...      ...   
2381       7415   65       1          0               2  21.132937        0   
2384       7418   31       0          0               2  31.821008        1   
2387       7421   43       1          0               2  29.059613        0   
2388       7422   18       1          0               1  20.740850        0   
2389       7423   54       0          3               2  37.079560        0   

      PhysicalActivity  DietQuality  SleepQuality  ...  \
1314          2.823038     0.510640      5.518425  ...   
277           9.446850     2.115253      7.111962  ...   
936           2.589260     5.305714      4.396984  ...   
267           9.733332     7.110281      5.372597  ...   
1192          3.950407     8.817213      6.830347  ...   
...                ...          ...           ...  ...   
2381          7.024412     2.935468      6.105681  ...   
2384          8.516835     3.532328      9.442670  ...   
2387          3.019854     6.119637      8.300960  ...   
2388          5.805180     4.386992      7.731192  ...   
2389          4.735169     8.214064      7.483521  ...   

      GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
1314                       0          2.581002         4.283310         0   
277                        0          1.683750         5.062565         1   
936                        0          3.703655         1.742685         1   
267                        0          1.398853         4.282494         1   
1192                       0          3.760390         3.091618         1   
...                      ...               ...              ...       ...   
2381                       0          2.794848         5.309860         0   
2384                       1          1.883568         2.592148         0   
2387                       0          3.125249         5.166032         0   
2388                       0          1.132977         5.509502         0   
2389                       0          1.685962         3.346877         1   

      ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
1314                  1               1         0                  0   
277                   0               0         1                  1   
936                   0               1         1                  0   
267                   1               0         0                  0   
1192                  0               0         1                  1   
...                 ...             ...       ...                ...   
2381                  0               0         1                  1   
2384                  0               0         0                  1   
2387                  1               0         0                  0   
2388                  0               0         1                  1   
2389                  0               1         1                  0   

      ExerciseInduced  Diagnosis  
1314                1          0  
277                 1          0  
936                 1          0  
267                 1          0  
1192                0          0  
...               ...        ...  
2381                1          1  
2384                1          1  
2387                1          1  
2388                0          1  
2389                1          1  

[248 rows x 28 columns]

In [99]:
data['Diagnosis'].value_counts()

0    124
1    124
Name: Diagnosis, dtype: int64

In [100]:
data.groupby('Diagnosis').mean()

PatientID        Age  Gender  Ethnicity  EducationLevel  \
Diagnosis                                                              
0          6169.911290  40.032258     0.5   0.758065         1.33871   
1          7307.032258  40.741935     0.5   0.741935         1.33871   

                 BMI   Smoking  PhysicalActivity  DietQuality  SleepQuality  \
Diagnosis                                                                     
0          28.157789  0.137097          5.348814     5.125821      7.109072   
1          26.859284  0.112903          5.114679     4.983685      7.152516   

           ...  HayFever  GastroesophagealReflux  LungFunctionFEV1  \
Diagnosis  ...                                                       
0          ...  0.298387                0.153226          2.507984   
1          ...  0.217742                0.193548          2.634555   

           LungFunctionFVC  Wheezing  ShortnessOfBreath  ChestTightness  \
Diagnosis                                                                 
0                 3.735155  0.629032           0.467742        0.500000   
1                 3.906432  0.653226           0.467742        0.419355   

           Coughing  NighttimeSymptoms  ExerciseInduced  
Diagnosis                                                
0          0.427419           0.588710         0.588710  
1          0.451613           0.556452         0.717742  

[2 rows x 27 columns]

In [101]:
data.to_csv("asthma.csv", index=False)

**Logistic Regression model**

In [102]:
input_data = data.drop(columns = ["Diagnosis"], axis=1)
output_data = data["Diagnosis"]
input_data

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
1314       6348   50       1          0               2  33.187808        0   
277        5311   25       0          0               1  31.720048        0   
936        5970   37       0          1               0  33.728561        0   
267        5301   47       0          1               0  35.866880        0   
1192       6226   34       1          0               0  32.722947        0   
...         ...  ...     ...        ...             ...        ...      ...   
2381       7415   65       1          0               2  21.132937        0   
2384       7418   31       0          0               2  31.821008        1   
2387       7421   43       1          0               2  29.059613        0   
2388       7422   18       1          0               1  20.740850        0   
2389       7423   54       0          3               2  37.079560        0   

      PhysicalActivity  DietQuality  SleepQuality  ...  HayFever  \
1314          2.823038     0.510640      5.518425  ...         0   
277           9.446850     2.115253      7.111962  ...         0   
936           2.589260     5.305714      4.396984  ...         1   
267           9.733332     7.110281      5.372597  ...         0   
1192          3.950407     8.817213      6.830347  ...         0   
...                ...          ...           ...  ...       ...   
2381          7.024412     2.935468      6.105681  ...         0   
2384          8.516835     3.532328      9.442670  ...         0   
2387          3.019854     6.119637      8.300960  ...         0   
2388          5.805180     4.386992      7.731192  ...         0   
2389          4.735169     8.214064      7.483521  ...         1   

      GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
1314                       0          2.581002         4.283310         0   
277                        0          1.683750         5.062565         1   
936                        0          3.703655         1.742685         1   
267                        0          1.398853         4.282494         1   
1192                       0          3.760390         3.091618         1   
...                      ...               ...              ...       ...   
2381                       0          2.794848         5.309860         0   
2384                       1          1.883568         2.592148         0   
2387                       0          3.125249         5.166032         0   
2388                       0          1.132977         5.509502         0   
2389                       0          1.685962         3.346877         1   

      ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
1314                  1               1         0                  0   
277                   0               0         1                  1   
936                   0               1         1                  0   
267                   1               0         0                  0   
1192                  0               0         1                  1   
...                 ...             ...       ...                ...   
2381                  0               0         1                  1   
2384                  0               0         0                  1   
2387                  1               0         0                  0   
2388                  0               0         1                  1   
2389                  0               1         1                  0   

      ExerciseInduced  
1314                1  
277                 1  
936                 1  
267                 1  
1192                0  
...               ...  
2381                1  
2384                1  
2387                1  
2388                0  
2389                1  

[248 rows x 27 columns]

In [103]:
output_data

1314    0
277     0
936     0
267     0
1192    0
       ..
2381    1
2384    1
2387    1
2388    1
2389    1
Name: Diagnosis, Length: 248, dtype: int64

In [104]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size = 0.2, stratify=output_data, random_state=2)

In [105]:
LR = LogisticRegression()

In [106]:
LR.fit(x_train, y_train)

LogisticRegression()

In [107]:
predict = LR.predict(x_test)

In [108]:
predict

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0])

In [109]:
x_train.head(1)

PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
2154       7188   69       1          0               2  18.094707        0   

      PhysicalActivity  DietQuality  SleepQuality  ...  HayFever  \
2154          5.648944      4.73622       8.94694  ...         1   

      GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
2154                       1          2.076774         1.993044         0   

      ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
2154                  1               1         0                  1   

      ExerciseInduced  
2154                0  

[1 rows x 27 columns]

In [110]:
x_train.columns

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'LungFunctionFEV1', 'LungFunctionFVC',
       'Wheezing', 'ShortnessOfBreath', 'ChestTightness', 'Coughing',
       'NighttimeSymptoms', 'ExerciseInduced'],
      dtype='object')

In [111]:
inputdata = pd.DataFrame(
    [[6453,40,1,0,1,28.54,1,0.9885,7.56,6.456,4.678,3.54,0.45,0,1,1,0,0,1,1.345,3.656,1,1,1,0,1,0]],
    columns = ['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'LungFunctionFEV1', 'LungFunctionFVC',
       'Wheezing', 'ShortnessOfBreath', 'ChestTightness', 'Coughing',
       'NighttimeSymptoms', 'ExerciseInduced'])

In [112]:
inputdata

PatientID  Age  Gender  Ethnicity  EducationLevel    BMI  Smoking  \
0       6453   40       1          0               1  28.54        1   

   PhysicalActivity  DietQuality  SleepQuality  ...  HayFever  \
0            0.9885         7.56         6.456  ...         0   

   GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
0                       1             1.345            3.656         1   

   ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
0                  1               1         0                  1   

   ExerciseInduced  
0                0  

[1 rows x 27 columns]

In [113]:
Logistic = LR.predict(inputdata)

In [114]:
Logistic

array([1])

In [115]:
accuracy = accuracy_score(y_test, predict)
print(f'Accuracy: {accuracy}')

Accuracy: 0.72


**Decision Tree Classifier**

In [116]:
DTC = DecisionTreeClassifier()

In [117]:
DTC.fit(x_train, y_train)

DecisionTreeClassifier()

In [118]:
predictions = DTC.predict(x_test)

In [119]:
predictions

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1])

In [120]:
decisiondata = pd.DataFrame(
    [[6453,40,1,0,1,28.54,1,0.9885,7.56,6.456,4.678,3.54,0.45,0,1,1,0,0,1,1.345,3.656,1,1,1,0,1,0]],
    columns = ['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'LungFunctionFEV1', 'LungFunctionFVC',
       'Wheezing', 'ShortnessOfBreath', 'ChestTightness', 'Coughing',
       'NighttimeSymptoms', 'ExerciseInduced'])

In [121]:
decisiondata

PatientID  Age  Gender  Ethnicity  EducationLevel    BMI  Smoking  \
0       6453   40       1          0               1  28.54        1   

   PhysicalActivity  DietQuality  SleepQuality  ...  HayFever  \
0            0.9885         7.56         6.456  ...         0   

   GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
0                       1             1.345            3.656         1   

   ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
0                  1               1         0                  1   

   ExerciseInduced  
0                0  

[1 rows x 27 columns]

In [122]:
Decision = DTC.predict(decisiondata)

In [123]:
Decision

array([0])

In [124]:
accuracy = accuracy_score(y_test, predictions)
print(f'Accuracy: {accuracy}')

Accuracy: 0.92


**Random Forest Classifier**

In [125]:
RFC = RandomForestClassifier()

In [126]:
RFC.fit(x_train, y_train)

RandomForestClassifier()

In [127]:
prediction = RFC.predict(x_test)

In [128]:
prediction

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1])

In [129]:
Randomdata = pd.DataFrame(
    [[6453,40,1,0,1,28.54,1,0.9885,7.56,6.456,4.678,3.54,0.45,0,1,1,0,0,1,1.345,3.656,1,1,1,0,1,0]],
    columns = ['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'LungFunctionFEV1', 'LungFunctionFVC',
       'Wheezing', 'ShortnessOfBreath', 'ChestTightness', 'Coughing',
       'NighttimeSymptoms', 'ExerciseInduced'])

In [130]:
Randomdata

PatientID  Age  Gender  Ethnicity  EducationLevel    BMI  Smoking  \
0       6453   40       1          0               1  28.54        1   

   PhysicalActivity  DietQuality  SleepQuality  ...  HayFever  \
0            0.9885         7.56         6.456  ...         0   

   GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
0                       1             1.345            3.656         1   

   ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
0                  1               1         0                  1   

   ExerciseInduced  
0                0  

[1 rows x 27 columns]

In [131]:
Random = RFC.predict(decisiondata)

In [132]:
Random

array([0])

In [133]:
accuracy = accuracy_score(y_test, prediction)
print(f'Accuracy: {accuracy}')

Accuracy: 0.96


**Support Vector Machines**

In [134]:
SVC = SVC()

In [135]:
SVC.fit(x_train, y_train)

SVC()

In [136]:
SVMpredictions = SVC.predict(x_test)

In [137]:
SVMpredictions

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1])

In [138]:
SVMdata = pd.DataFrame(
    [[6453,40,1,0,1,28.54,1,0.9885,7.56,6.456,4.678,3.54,0.45,0,1,1,0,0,1,1.345,3.656,1,1,1,0,1,0]],
    columns = ['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'PollutionExposure', 'PollenExposure', 'DustExposure', 'PetAllergy',
       'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
       'GastroesophagealReflux', 'LungFunctionFEV1', 'LungFunctionFVC',
       'Wheezing', 'ShortnessOfBreath', 'ChestTightness', 'Coughing',
       'NighttimeSymptoms', 'ExerciseInduced'])

In [139]:
SVMdata

PatientID  Age  Gender  Ethnicity  EducationLevel    BMI  Smoking  \
0       6453   40       1          0               1  28.54        1   

   PhysicalActivity  DietQuality  SleepQuality  ...  HayFever  \
0            0.9885         7.56         6.456  ...         0   

   GastroesophagealReflux  LungFunctionFEV1  LungFunctionFVC  Wheezing  \
0                       1             1.345            3.656         1   

   ShortnessOfBreath  ChestTightness  Coughing  NighttimeSymptoms  \
0                  1               1         0                  1   

   ExerciseInduced  
0                0  

[1 rows x 27 columns]

In [140]:
SVM = SVC.predict(SVMdata)

In [141]:
SVM

array([0])

In [142]:
accuracy = accuracy_score(y_test, SVMpredictions)
print(f'Accuracy: {accuracy}')

Accuracy: 0.88


**K Neighbors Classifier**

In [143]:
KNC = KNeighborsClassifier()

In [144]:
KNC.fit(x_train, y_train)

KNeighborsClassifier()

In [145]:
KNpredictions = KNC.predict(x_test)

In [146]:
KNpredictions

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1])

In [147]:
accuracy = accuracy_score(y_test, KNpredictions)
print(f'Accuracy: {accuracy}')

Accuracy: 0.96


**Gradient Boosting Classifier**

In [148]:
GBC = GradientBoostingClassifier()

In [149]:
GBC.fit(x_train, y_train)

GradientBoostingClassifier()

In [150]:
GBCpredictions = GBC.predict(x_test)

In [151]:
GBCpredictions

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1])

In [152]:
accuracy = accuracy_score(y_test, GBCpredictions)
print(f'Accuracy: {accuracy}')

Accuracy: 0.96


**XGBoost Classifier**

In [153]:
xgb = xgb.XGBClassifier()

In [154]:
xgb.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [155]:
XGBpredictions = xgb.predict(x_test)

In [156]:
XGBpredictions

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1])

In [157]:
accuracy = accuracy_score(y_test, XGBpredictions)
print(f'Accuracy: {accuracy}')

Accuracy: 0.96


**Artificial Neural Networks**

In [158]:
ANN = MLPClassifier()

In [159]:
ANN.fit(x_train, y_train)

MLPClassifier()

In [160]:
MLPpredictions = ANN.predict(x_test)

In [161]:
MLPpredictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [162]:
accuracy = accuracy_score(y_test, MLPpredictions)
print(f'Accuracy: {accuracy}')

Accuracy: 0.5


**CONCLUSION**

**The Best Model for this Classification Problem is the GRADIENT BOOST CLASSIFIER WITH:**
    **Accuracy: 0.9457202505219207**

In [164]:
import pickle
pickle_out = open("GBC.pkl", "wb")
pickle.dump(GBC,pickle_out)
pickle_out.close()